# Generated by Django 3.1.2 on 2020-11-05 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('rush_yds', models.IntegerField()),
                ('att', models.IntegerField()),
                ('td', models.IntegerField()),
                ('twenty', models.IntegerField()),
                ('fourty', models.IntegerField()),
                ('long', models.IntegerField()),
                ('rush_1st', models.IntegerField()),
                ('rush_1st_perc', models.IntegerField()),
                ('rush_fum', models.IntegerField()),
            ],
        ),
    ]
