# Generated by Django 3.1.2 on 2020-11-09 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_rb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defense',
            fields=[
                ('team', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('g_p', models.IntegerField()),
                ('yds', models.IntegerField()),
                ('yds_g', models.FloatField()),
                ('pass_yds', models.IntegerField()),
                ('pass_yds_g', models.FloatField()),
                ('rush_yds', models.IntegerField()),
                ('rush_yds_g', models.FloatField()),
                ('points', models.IntegerField()),
                ('point_g', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='qb',
            name='id',
        ),
        migrations.RemoveField(
            model_name='rb',
            name='id',
        ),
        migrations.AlterField(
            model_name='qb',
            name='att',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='qb',
            name='cmp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='qb',
            name='first',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='qb',
            name='int',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='qb',
            name='lng',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='qb',
            name='more_20',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='qb',
            name='more_40',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='qb',
            name='name',
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='qb',
            name='pass_yds',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='qb',
            name='qb_rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='qb',
            name='sack',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='qb',
            name='sack_Y',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='qb',
            name='td',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rb',
            name='name',
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
    ]
