# Generated by Django 3.1.2 on 2020-11-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_rb_rush_yds_att'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qb',
            name='qb_rating',
            field=models.FloatField(),
        ),
    ]
